#!/usr/bin/env python3
"""Build the downloadable edition of the reader from the generated pages.

The book is a third presentation of the same governed corpus, after the
translation surfaces themselves and the website. It is assembled from
`reader-src/`, not from `docs/translations/`, so that it inherits the reader
titles, newcomer guidance, preserved legacy introductions, and the reading
order -- everything that makes the website readable rather than archival.

Four things are dropped on the way in, because they are website furniture
with no meaning in a book:

  * the "generated by" banner comment at the top of each page
  * the skip-to-translation link
  * the previous/all/next navigation block at the bottom
  * the per-page visible terms panel and inline abbreviation definitions; the
    full glossary is included as an appendix instead

Usage:

    python scripts/build_book.py --check    verify pandoc is available
    python scripts/build_book.py            build into site/downloads/

Requires pandoc. On the deploy runner it comes from apt; locally, set the
PANDOC environment variable if it is not on PATH.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

try:
    from scripts.surface_registry import (
        STAGES,
        REPO_ROOT,
        display_title,
        reader_meta,
        surfaces_in_reading_order,
    )
except ModuleNotFoundError:  # invoked as a script from the repo root
    from surface_registry import (  # type: ignore[no-redef]
        STAGES,
        REPO_ROOT,
        display_title,
        reader_meta,
        surfaces_in_reading_order,
    )


READER_DIR = REPO_ROOT / "reader-src"
SUTTA_DIR = READER_DIR / "suttas"
DEFAULT_OUT = REPO_ROOT / "site" / "downloads"
BOOK_STEM = "osf-pali-readings"

TITLE = "OSF Pali Readings"
SUBTITLE = "Early Buddhist discourses in plain, contemporary English"
AUTHOR = "Open Sangha Foundation"

HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
ABBR_LINE = re.compile(r"^\*\[[^\]]+\]:.*$", re.M)
SKIP_LINK_LINE = re.compile(
    r"^\[Skip to the translation\]\(#translation\)\{[^\n]*\}\s*$",
    re.M,
)
TERMS_DETAILS = re.compile(
    r"\s*<details\b(?=[^>]*\bclass=[\"'][^\"']*\breader-terms\b[^\"']*[\"'])"
    r"[^>]*>.*?</details>\s*",
    re.IGNORECASE | re.DOTALL,
)
READING_NAV = re.compile(
    r"\s*(?:---\s*)?<nav\b"
    r"(?=[^>]*\bclass=[\"'][^\"']*\breading-order\b[^\"']*[\"'])"
    r"[^>]*>.*?</nav>\s*",
    re.IGNORECASE | re.DOTALL,
)
HEADING = re.compile(r"^(#{1,6})( )", re.M)
BLANK_RUN = re.compile(r"\n{3,}")


# --------------------------------------------------------------------------
# pandoc
# --------------------------------------------------------------------------

def find_pandoc() -> str | None:
    """Locate pandoc, preferring an explicit override.

    winget installs pandoc under LOCALAPPDATA rather than Program Files and
    does not always put it on PATH for the current shell, so that location is
    checked before giving up.
    """
    override = os.environ.get("PANDOC")
    if override and Path(override).exists():
        return override

    found = shutil.which("pandoc")
    if found:
        return found

    local = os.environ.get("LOCALAPPDATA")
    if local:
        candidate = Path(local) / "Pandoc" / "pandoc.exe"
        if candidate.exists():
            return str(candidate)
    return None


# --------------------------------------------------------------------------
# assembling the manuscript
# --------------------------------------------------------------------------

def strip_web_furniture(text: str) -> str:
    """Remove the parts of a reader page that only make sense on the web."""
    text = HTML_COMMENT.sub("", text)
    text = SKIP_LINK_LINE.sub("", text)
    text = TERMS_DETAILS.sub("\n", text)
    text = READING_NAV.sub("\n", text)
    text = ABBR_LINE.sub("", text)
    return text


def demote(text: str, levels: int = 1) -> str:
    """Push every heading down, so pages can nest under book-level parts."""
    return HEADING.sub(lambda m: "#" * (len(m.group(1)) + levels) + m.group(2), text)


def tidy(text: str) -> str:
    return BLANK_RUN.sub("\n\n", text).strip()


def sutta_chapter(surface) -> str:
    path = SUTTA_DIR / surface.main_name
    body = strip_web_furniture(path.read_text(encoding="utf-8"))
    return tidy(demote(body))


def front_matter() -> str:
    return "\n".join([
        "---",
        f'title: "{TITLE}"',
        f'subtitle: "{SUBTITLE}"',
        f'author: "{AUTHOR}"',
        "lang: en",
        "---",
        "",
    ])


def how_this_book_is_arranged() -> str:
    """A short orientation, replacing the site's Start Here page.

    Start Here itself is not reused: it is a page of links into the website,
    and in a book those links have nowhere to go. The reading order it
    describes is preserved as the order of the book itself.
    """
    lines = [
        "# How this book is arranged",
        "",
        "The texts are not in canonical order. They are arranged for someone "
        "reading this material for the first time, in five sets that move "
        "from the least technical to the most:",
        "",
    ]
    for number, title, blurb in STAGES:
        lines.append(f"**Set {number} — {title}.** {blurb}")
        lines.append("")
    lines.extend([
        "Each text opens with a short note on what it is doing and why it "
        "sits where it does. Words carrying technical weight are collected "
        "in the glossary at the end.",
        "",
        "Nothing here needs to be read in order, and the later sets assume "
        "the vocabulary of the earlier ones rather than requiring them.",
    ])
    return "\n".join(lines)


def appendix(path: Path) -> str:
    return tidy(strip_web_furniture(path.read_text(encoding="utf-8")))


def manuscript() -> str:
    parts: list[str] = [front_matter()]

    parts.append(appendix(READER_DIR / "about.md"))
    parts.append(how_this_book_is_arranged())

    by_stage: dict[int, list] = {}
    for surface in surfaces_in_reading_order():
        by_stage.setdefault(reader_meta(surface).stage, []).append(surface)

    for number, title, blurb in STAGES:
        surfaces = by_stage.get(number, [])
        if not surfaces:
            continue
        parts.append(f"# Set {number} — {title}\n\n{blurb}")
        for surface in surfaces:
            parts.append(sutta_chapter(surface))

    parts.append(appendix(READER_DIR / "glossary.md"))
    return "\n\n".join(parts) + "\n"


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------

def split_flag(pandoc: str) -> str:
    """The flag that splits the EPUB into one file per sutta.

    pandoc renamed `--epub-chapter-level` to `--split-level` in 3.5. The old
    name still works but warns, and will eventually be removed; the new name
    does not exist on older builds. The deploy runner installs whatever pandoc
    its distribution ships, so pick based on what this binary actually
    advertises rather than assuming a version.
    """
    try:
        helptext = subprocess.run(
            [pandoc, "--help"],
            capture_output=True, text=True, check=False,
        ).stdout
    except OSError:
        helptext = ""
    return "--split-level=2" if "--split-level" in helptext else "--epub-chapter-level=2"


def build(out_dir: Path, pandoc: str) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    source = out_dir / f"{BOOK_STEM}.md"
    source.write_text(manuscript(), encoding="utf-8")

    target = out_dir / f"{BOOK_STEM}.epub"
    subprocess.run(
        [
            pandoc, str(source),
            "--from", "markdown",
            "--to", "epub3",
            "--output", str(target),
            "--toc",
            "--toc-depth=2",
            split_flag(pandoc),
            "--standalone",
        ],
        check=True,
        cwd=REPO_ROOT,
    )
    source.unlink()
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Report whether pandoc is available, and build nothing.",
    )
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT,
        help="Directory to write the book into (default: site/downloads).",
    )
    args = parser.parse_args()

    pandoc = find_pandoc()
    if args.check:
        print(f"pandoc: {pandoc}" if pandoc else "pandoc: not found")
        return 0 if pandoc else 1

    if not pandoc:
        print(
            "pandoc not found. Install it, or set PANDOC to its full path.",
            file=sys.stderr,
        )
        return 1

    target = build(args.out, pandoc)
    size = target.stat().st_size
    surfaces = len(list(surfaces_in_reading_order()))
    print(f"Book: {target.relative_to(REPO_ROOT)} ({surfaces} texts, {size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
