#!/usr/bin/env python3
"""Generate the reader's edition from the governed translation corpus.

The reader is a presentation layer, never a second source of truth. Everything
it shows about a sutta comes from two places:

  docs/translations/<surface>.md   the canonical governed translation
  scripts/surface_registry.py      reader metadata (title, stage, path note)

and two reader-facing sources:

  includes/newcomer-guides/<surface>.json  structured orientation for the
                                         Essential Five
  the legacy "About this text" / "Before you read" block inside each other
  reader page, which is preserved across regeneration

Everything else -- the page title, the reference line, the translation body,
the reading-path navigation, the per-page glossary, the All Suttas index, the
Start Here path, the home page, the glossary page, and the site navigation --
is generated from those sources and is safe to regenerate at any time.

Usage:

    python scripts/generate_reader.py --check   verify the reader is current
    python scripts/generate_reader.py --write   regenerate it

`--check` is part of `run_checks.py`, so a reader that has drifted from the
governed corpus fails the build rather than going out stale.
"""

from __future__ import annotations

import argparse
import difflib
import html
import json
import math
import re
import sys
from pathlib import Path

try:
    from scripts.surface_registry import (
        ESSENTIAL_FIVE,
        READER_METADATA,
        STAGES,
        TRANSLATION_SURFACES,
        TranslationSurface,
        REPO_ROOT,
        display_title,
        reader_meta,
        surfaces_in_reading_order,
    )
except ModuleNotFoundError:  # invoked as a script from the repo root
    from surface_registry import (  # type: ignore[no-redef]
        ESSENTIAL_FIVE,
        READER_METADATA,
        STAGES,
        TRANSLATION_SURFACES,
        TranslationSurface,
        REPO_ROOT,
        display_title,
        reader_meta,
        surfaces_in_reading_order,
    )


READER_DIR = REPO_ROOT / "reader-src"
SUTTA_DIR = READER_DIR / "suttas"
GLOSSARY_SOURCE = REPO_ROOT / "includes" / "glossary.md"
GUIDES_DIR = REPO_ROOT / "includes" / "newcomer-guides"
TERMS_DIR = REPO_ROOT / "terms"
MKDOCS = REPO_ROOT / "mkdocs.yml"

BODY_MARKER = "## Translation"
INTRO_HEADINGS = {"about this text", "before you read"}
WORDS_PER_MINUTE = 180
NAV_BEGIN = "  # BEGIN GENERATED SUTTA NAV"
NAV_END = "  # END GENERATED SUTTA NAV"

GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_reader.py. The translation body is a\n"
    "     presentation copy of the governed surface named above; edit that file,\n"
    "     not this one. Newcomer guidance comes from includes/newcomer-guides;\n"
    "     legacy reader introductions are preserved across regeneration. -->"
)

DEFAULT_INTRO = (
    "You can read this translation straight through. When a recurring term "
    "needs explanation, its plain-English definition is available in the "
    "words-used panel below the translation."
)


# --------------------------------------------------------------------------
# reading the canonical surface
# --------------------------------------------------------------------------

def surface_body(text: str) -> str:
    """Return the governed translation body without changing its contents."""
    if BODY_MARKER not in text:
        raise ValueError(f"surface has no `{BODY_MARKER}` section")
    body = text.split(BODY_MARKER, 1)[1].strip()
    # A consistent opening heading gives every reader page a sound hierarchy:
    # H1 title, H2 orientation, H2 Translation, then the governed H3 sections.
    if not body.startswith("### "):
        raise ValueError(
            "surface body must open with a `### ` heading; found: "
            f"{body.splitlines()[0][:60]!r}"
        )
    return body


def existing_intro(path: Path) -> str | None:
    """Preserve a legacy reader-authored orientation block, when present."""
    if not path.exists():
        return None
    lines = path.read_text(encoding="utf-8").splitlines()
    start = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("## "):
            continue
        heading = stripped[3:].strip().casefold()
        if heading in INTRO_HEADINGS:
            start = index + 1
            continue
        if start is not None:
            return "\n".join(lines[start:index]).strip()
    if start is not None:
        return "\n".join(lines[start:]).strip()
    return None


def translation_word_count(body: str) -> int:
    """A stable, reader-facing word count for a governed Markdown body."""
    plain = re.sub(r"<!--.*?-->", " ", body, flags=re.S)
    plain = re.sub(r"`([^`]*)`", r"\1", plain)
    plain = re.sub(r"!?\[([^]]+)\]\([^)]+\)", r"\1", plain)
    plain = re.sub(r"<[^>]+>", " ", plain)
    return len(re.findall(r"\b[\w’'-]+\b", plain, flags=re.UNICODE))


def reading_stats(body: str) -> tuple[int, int]:
    words = translation_word_count(body)
    return words, max(1, math.ceil(words / WORDS_PER_MINUTE))


# --------------------------------------------------------------------------
# per-page glossary
# --------------------------------------------------------------------------

def load_glossary() -> dict[str, str]:
    """Reader-facing term glosses, keyed by the English surface string.

    The source is `includes/glossary.md`, whose definitions are written for
    non-specialist readers. It is deliberately not the editorial `notes` field from the
    term records, which is written for contributors.
    """
    if not GLOSSARY_SOURCE.exists():
        return {}
    entries: dict[str, str] = {}
    for line in GLOSSARY_SOURCE.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\*\[([^\]]+)\]:\s*(.+)$", line.strip())
        if match:
            entries[match.group(1)] = match.group(2).strip()
    return entries


def glossary_abbreviations_for_page(
    body: str,
    glossary: dict[str, str],
) -> list[tuple[str, str]]:
    """Exact-case definitions that can become inline abbreviation notes."""
    return [
        (term, gloss)
        for term, gloss in sorted(glossary.items(), key=lambda item: item[0].casefold())
        if re.search(rf"(?<!\w){re.escape(term)}(?!\w)", body)
    ]


def glossary_for_page(body: str, glossary: dict[str, str]) -> list[tuple[str, str]]:
    """Visible glossary entries whose term actually appears on this page.

    Injecting per page rather than appending the whole glossary to every page
    is what makes a term able to carry a different note in a different sutta:
    the definition now travels with the page instead of being global.

    Exact capitalization remains meaningful where it carries a different
    gloss (`Dhamma` and `dhamma`). Case variants with the same definition are
    collapsed for the visible list, while inline abbreviations stay exact-case.
    """
    exact = glossary_abbreviations_for_page(body, glossary)
    exact_folded_terms = {term.casefold() for term, _ in exact}
    found: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for term, gloss in exact:
        identity = (term.casefold(), gloss)
        if identity not in seen:
            found.append((term, gloss))
            seen.add(identity)

    # A sentence-initial capitalization may not have its own glossary entry.
    # Add a case-insensitive fallback only for definitions not already shown.
    for term, gloss in sorted(glossary.items(), key=lambda item: item[0].casefold()):
        if term.casefold() in exact_folded_terms:
            continue
        identity = (term.casefold(), gloss)
        if identity in seen:
            continue
        if re.search(rf"(?<!\w){re.escape(term)}(?!\w)", body, flags=re.I):
            found.append((term, gloss))
            seen.add(identity)
    return sorted(found, key=lambda item: item[0].casefold())


def glossary_entry(term: str, glossary: dict[str, str]) -> tuple[str, str]:
    """Resolve a guide term without making capitalization a second concept."""
    matches = [(key, value) for key, value in glossary.items()
               if key.casefold() == term.casefold()]
    if not matches:
        raise ValueError(f"newcomer guide uses unknown glossary term {term!r}")
    return matches[0]


GUIDE_TEXT_FIELDS = (
    "scene", "question", "main_point", "reading_cue", "not_saying",
)


def load_newcomer_guides(
    glossary: dict[str, str] | None = None,
) -> dict[str, dict[str, object]]:
    """Load and validate the structured newcomer guides.

    Evidence headings and key terms are checked against the governed corpus so
    an orientation note cannot silently drift away from the text it describes.
    """
    glossary = glossary if glossary is not None else load_glossary()
    surfaces = {surface.key: surface for surface in TRANSLATION_SURFACES}
    guides: dict[str, dict[str, object]] = {}
    if not GUIDES_DIR.exists():
        raise ValueError("includes/newcomer-guides is missing")
    for path in sorted(GUIDES_DIR.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as error:
            raise ValueError(f"{path.name}: cannot load guide: {error}") from error
        if not isinstance(data, dict):
            raise ValueError(f"{path.name}: guide must be a JSON object")
        key = data.get("surface_key")
        if not isinstance(key, str) or not key:
            raise ValueError(f"{path.name}: surface_key must be a nonempty string")
        if path.stem != key:
            raise ValueError(f"{path.name}: filename and surface_key disagree")
        if key not in surfaces:
            raise ValueError(f"{path.name}: surface_key is not registered")
        if key not in ESSENTIAL_FIVE:
            raise ValueError(f"{path.name}: guides are currently limited to Essential Five")
        if key in guides:
            raise ValueError(f"{path.name}: duplicate guide for {key}")
        for field in GUIDE_TEXT_FIELDS:
            if not isinstance(data.get(field), str) or not str(data[field]).strip():
                raise ValueError(f"{path.name}: {field} must be a nonempty string")
        key_terms = data.get("key_terms")
        if (not isinstance(key_terms, list) or not 3 <= len(key_terms) <= 6
                or any(not isinstance(term, str) or not term.strip()
                       for term in key_terms)):
            raise ValueError(f"{path.name}: key_terms must contain 3 to 6 terms")
        evidence = data.get("evidence_sections")
        if (not isinstance(evidence, list) or not evidence
                or any(not isinstance(heading, str) or not heading.strip()
                       for heading in evidence)):
            raise ValueError(f"{path.name}: evidence_sections must be nonempty strings")
        body = surface_body(surfaces[key].main_path.read_text(encoding="utf-8"))
        headings = set(re.findall(r"^###\s+(.+?)\s*$", body, flags=re.M))
        for heading in evidence:
            if heading not in headings:
                raise ValueError(
                    f"{path.name}: evidence section {heading!r} is not a governed heading"
                )
        for term in key_terms:
            glossary_entry(term, glossary)
            if not re.search(rf"(?<!\w){re.escape(term)}(?!\w)", body, flags=re.I):
                raise ValueError(f"{path.name}: key term {term!r} is absent from the text")
        guides[key] = data
    missing = set(ESSENTIAL_FIVE) - set(guides)
    if missing:
        raise ValueError(
            "newcomer guides missing for Essential Five: " + ", ".join(sorted(missing))
        )
    return guides


def load_term_records() -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    if not TERMS_DIR.exists():
        return records
    for path in sorted(TERMS_DIR.rglob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if isinstance(data, dict):
            records.append(data)
    return records


# --------------------------------------------------------------------------
# page rendering
# --------------------------------------------------------------------------

def render_guide(guide: dict[str, object], glossary: dict[str, str]) -> list[str]:
    labels = (
        ("What happens", "scene"),
        ("Central question", "question"),
        ("Main point", "main_point"),
        ("Reading tip", "reading_cue"),
        ("This text is not saying", "not_saying"),
    )
    lines = ['<div class="reader-guide" markdown="1">', ""]
    for label, field in labels:
        lines.extend([f"### {label}", "", str(guide[field]).strip(), ""])
    lines.extend(["### Key words", "", '<dl class="reader-guide__terms">'])
    for requested in guide["key_terms"]:  # type: ignore[union-attr]
        term, gloss = glossary_entry(str(requested), glossary)
        lines.append(f"<dt><dfn>{html.escape(term)}</dfn></dt>")
        lines.append(f"<dd>{html.escape(gloss)}</dd>")
    lines.extend(["</dl>", "", "</div>"])
    return lines


def render_terms_panel(entries: list[tuple[str, str]]) -> list[str]:
    count = len(entries)
    noun = "word" if count == 1 else "words"
    lines = [
        '<details class="reader-terms">',
        f"<summary>{noun.capitalize()} used in this translation ({count})</summary>",
        "<dl>",
    ]
    for term, gloss in entries:
        lines.append(f"<dt><dfn>{html.escape(term)}</dfn></dt>")
        lines.append(f"<dd>{html.escape(gloss)}</dd>")
    lines.extend(["</dl>", "</details>"])
    return lines


def render_reading_nav(
    previous: TranslationSurface | None,
    following: TranslationSurface | None,
) -> list[str]:
    items: list[tuple[str, str]] = []
    if previous is not None:
        items.append((previous.main_name, f"← {display_title(previous)}"))
    items.append(("index.md", "All suttas"))
    if following is not None:
        items.append((following.main_name, f"{display_title(following)} →"))
    # Keep Markdown links inside a semantic nav so MkDocs rewrites source .md
    # targets into the correct directory URLs for the built site.
    lines = [
        '<nav class="reading-order" aria-label="Reading order" markdown="1">',
        "",
    ]
    for target, label in items:
        lines.append(f"- [{label}]({target})")
    lines.extend(["", "</nav>"])
    return lines

def render_sutta_page(
    surface: TranslationSurface,
    intro: str | None,
    glossary: dict[str, str],
    previous: TranslationSurface | None,
    following: TranslationSurface | None,
    guide: dict[str, object] | None = None,
) -> str:
    meta = reader_meta(surface)
    body = surface_body(surface.main_path.read_text(encoding="utf-8"))
    words, minutes = reading_stats(body)
    stage_name = dict((n, t) for n, t, _ in STAGES)[meta.stage]

    lines = [
        GENERATED_BANNER,
        "",
        f"# {display_title(surface)}",
        "",
        f"*{surface.label}, the {meta.pali_title} — "
        f"set {meta.stage}, {stage_name}*",
        "",
        f'<p class="reading-meta"><strong>Reading time:</strong> about {minutes} min '
        f"· {words:,} words</p>",
        "",
        "[Skip to the translation](#translation){ .reader-skip-link }",
        "",
        "## Before you read",
        "",
    ]
    entries = glossary_for_page(body, glossary)
    abbreviations = glossary_abbreviations_for_page(body, glossary)
    if guide is not None:
        lines.extend(render_guide(guide, glossary))
    else:
        lines.append(intro.strip() if intro else DEFAULT_INTRO)
    lines.extend(["", "## Translation", "", body, ""])
    lines.extend(render_terms_panel(entries))
    lines.extend(["", "---", ""])
    lines.extend(render_reading_nav(previous, following))
    lines.append("")

    # Keep inline abbreviation definitions as a convenience for pointer users.
    # The visible terms panel above is the accessible, input-independent route.
    if abbreviations:
        lines.append("")
        for term, gloss in abbreviations:
            lines.append(f"*[{term}]: {gloss}")
    return "\n".join(lines).rstrip() + "\n"


def render_home() -> str:
    total = len(TRANSLATION_SURFACES)
    by_key = {s.key: s for s in TRANSLATION_SURFACES}
    essential_words = 0
    for key in ESSENTIAL_FIVE:
        body = surface_body(by_key[key].main_path.read_text(encoding="utf-8"))
        essential_words += translation_word_count(body)
    essential_minutes = max(1, math.ceil(essential_words / WORDS_PER_MINUTE))
    lines = [
        "# OSF Pali Readings",
        "",
        "Early Buddhist discourses in plain, contemporary English.",
        "",
        f"All {total} translations in this collection are readable here. Each "
        "one is backed by a governed Pali lexicon, so a term that matters is "
        "translated the same way every time it appears, and every translation "
        "decision has a written reason behind it. See "
        "[About this translation](about.md) for what that means in practice.",
        "",
        "## Start reading",
        "",
        "- [**Start Here**](start-here.md) — a newcomer-friendly reading order "
        f"through all {total} texts, arranged by what makes sense to read "
        "first rather than by editorial priority",
        "- [**All Suttas**](suttas/index.md) — the full collection, if you "
        "already know what you are looking for",
        "- [**Glossary**](glossary.md) — the recurring vocabulary, in plain "
        "English",
        # Deliberately a raw anchor rather than a Markdown link. The book is
        # built by scripts/build_book.py straight into the built site, after
        # MkDocs has run, so it is not among the source files MkDocs knows
        # about. A Markdown link here would fail `mkdocs build --strict` for
        # anyone building the site without pandoc installed, which is most
        # people editing a translation.
        '- <a href="downloads/osf-pali-readings.epub"><strong>Download the '
        "whole collection</strong></a> — EPUB, for e-readers, phones, and "
        "reading offline",
        "",
        "## If you only read five",
        "",
        "Together these give a compact first route through the collection: "
        f"about {essential_minutes} minutes of reading ({essential_words:,} words).",
        "",
    ]
    for key in ESSENTIAL_FIVE:
        surface = by_key[key]
        meta = reader_meta(surface)
        lines.append(
            f"- [**{display_title(surface)}**](suttas/{surface.main_name}) — "
            f"{surface.label}, {meta.pali_title}"
        )
    lines.extend([
        "",
        "## How to read these",
        "",
        "The translations use clear, common English. Each page gives a reading "
        "time and a short orientation before the governed translation. Where a "
        "word is doing technical work, open the words-used panel for a plain-"
        "English definition. Some browsers also show the same note when you "
        "point to a marked word.",
        "",
        "Repetition has been kept where the texts repeat. These were spoken "
        "and memorised, and the repeating is part of how they work.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def render_start_here() -> str:
    lines = [
        "# Start Here",
        "",
        f"A suggested order for reading the {len(TRANSLATION_SURFACES)} "
        "translations in this collection, for someone new to this material.",
        "",
        "This is deliberately **not** the project's internal translation "
        "roadmap. That roadmap ranks texts by editorial leverage — which "
        "translation next does the most to strengthen the lexicon. This page "
        "ranks the same texts by a different question: if you have never read "
        "early Buddhist material, what order actually makes sense? The two "
        "orderings often disagree, and that is expected.",
        "",
        "Every text below is readable on this site.",
        "",
    ]
    for number, title, blurb in STAGES:
        staged = [
            s for s in surfaces_in_reading_order()
            if reader_meta(s).stage == number
        ]
        lines.extend([f"## Set {number} — {title}", "", blurb, ""])
        for surface in staged:
            meta = reader_meta(surface)
            label = display_title(surface)
            suffix = f" ({surface.label}, {meta.pali_title})"
            lines.append(
                f"- [**{label}**](suttas/{surface.main_name}){suffix} — "
                f"{meta.path_note}"
            )
        lines.append("")

    by_key = {s.key: s for s in TRANSLATION_SURFACES}
    names = ", ".join(
        f"[{display_title(by_key[k])}](suttas/{by_key[k].main_name})"
        for k in ESSENTIAL_FIVE
    )
    lines.extend([
        "## If you only read five",
        "",
        f"{names}. Together they introduce how to test a teaching, which "
        "questions help practice, the basic diagnosis and path, the difference "
        "between pain and added suffering, and the examination of self.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def render_all_suttas() -> str:
    lines = [
        "# All Suttas",
        "",
        f"All {len(TRANSLATION_SURFACES)} translations, grouped by collection. "
        "If you would rather be guided, use [Start Here](../start-here.md).",
        "",
    ]
    collections = [
        ("DN", "Dīgha Nikāya", "the long discourses"),
        ("MN", "Majjhima Nikāya", "the middle-length discourses"),
        ("SN", "Saṁyutta Nikāya", "the connected discourses"),
        ("AN", "Aṅguttara Nikāya", "the numbered discourses"),
        ("Iti", "Itivuttaka", "the short sayings, in the Khuddaka Nikāya"),
    ]

    def sort_key(surface: TranslationSurface) -> tuple[int, int]:
        numbers = re.findall(r"\d+", surface.label)
        major = int(numbers[0]) if numbers else 0
        minor = int(numbers[1]) if len(numbers) > 1 else 0
        return major, minor

    for prefix, pali, gloss in collections:
        group = sorted(
            (s for s in TRANSLATION_SURFACES if s.label.startswith(prefix + " ")),
            key=sort_key,
        )
        if not group:
            continue
        lines.extend([f"## {pali} ({prefix}) — {gloss}", ""])
        for surface in group:
            meta = reader_meta(surface)
            note = meta.path_note.split(".")[0].strip() + "."
            lines.append(
                f"- [**{display_title(surface)}**]({surface.main_name}) — "
                f"{surface.label} · {meta.pali_title} · Set {meta.stage}. {note}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_glossary() -> str:
    glossary = load_glossary()
    records = load_term_records()

    by_rendering: dict[str, dict[str, object]] = {}
    for record in records:
        preferred = record.get("preferred_translation")
        if isinstance(preferred, str):
            by_rendering.setdefault(preferred.casefold(), record)

    lines = [
        "# Glossary",
        "",
        "The recurring vocabulary of these translations, in plain English.",
        "",
        "Every term here is governed: the project fixes one English rendering "
        "for each Pali term and uses it consistently, so that a word carrying "
        "technical weight does not quietly change meaning between texts. The "
        "explanations below are written for readers. The editorial reasoning "
        "behind each choice lives in the "
        "[repository](https://github.com/timedrapery/shiny-adventure/tree/main/terms).",
        "",
        "Each sutta also has a visible words-used panel. Some browsers show the "
        "same definitions on marked terms, but the panel works without hovering.",
        "",
        '<dl class="glossary-list">',
    ]
    seen_definitions: set[tuple[str, str]] = set()
    for term, gloss in sorted(glossary.items(), key=lambda kv: kv[0].casefold()):
        identity = (term.casefold(), gloss)
        if identity in seen_definitions:
            continue
        seen_definitions.add(identity)
        record = by_rendering.get(term.casefold())
        pali = ""
        if record is not None and isinstance(record.get("term"), str):
            pali = str(record["term"])
        pali_note = (
            f' <span class="glossary-pali" lang="pi">({html.escape(pali)})</span>'
            if pali else ""
        )
        lines.append(f"<dt><dfn>{html.escape(term)}</dfn>{pali_note}</dt>")
        lines.append(f"<dd>{html.escape(gloss)}</dd>")

    lines.extend([
        "</dl>",
        "",
        "## Terms deliberately left in Pali",
        "",
        "A few words are kept in Pali because every English option narrows "
        "them misleadingly. Where that is the case, the surrounding text is "
        "written so the sense is still followable.",
        "",
        "`bhikkhu`, `dhamma`, `nibbāna`, and `Tathāgata` are the main ones.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def render_nav() -> str:
    lines = []
    for number, title, _ in STAGES:
        staged = [
            s for s in surfaces_in_reading_order()
            if reader_meta(s).stage == number
        ]
        if not staged:
            continue
        lines.append(f"      - Set {number}. {title}:")
        for surface in staged:
            label = display_title(surface).replace('"', "'")
            lines.append(f'          - "{label}": suttas/{surface.main_name}')
    return "\n".join(lines)


# --------------------------------------------------------------------------
# planning
# --------------------------------------------------------------------------

def planned_files() -> dict[Path, str]:
    """Every file the generator owns, mapped to its intended content."""
    glossary = load_glossary()
    guides = load_newcomer_guides(glossary)
    ordered = surfaces_in_reading_order()
    planned: dict[Path, str] = {
        READER_DIR / "index.md": render_home(),
        READER_DIR / "start-here.md": render_start_here(),
        READER_DIR / "glossary.md": render_glossary(),
        SUTTA_DIR / "index.md": render_all_suttas(),
    }
    for position, surface in enumerate(ordered):
        page = SUTTA_DIR / surface.main_name
        planned[page] = render_sutta_page(
            surface,
            existing_intro(page),
            glossary,
            ordered[position - 1] if position else None,
            ordered[position + 1] if position + 1 < len(ordered) else None,
            guides.get(surface.key),
        )
    return planned


def planned_mkdocs() -> str:
    text = MKDOCS.read_text(encoding="utf-8")
    if NAV_BEGIN not in text or NAV_END not in text:
        raise ValueError("mkdocs.yml is missing the generated nav markers")
    head, rest = text.split(NAV_BEGIN, 1)
    _, tail = rest.split(NAV_END, 1)
    return f"{head}{NAV_BEGIN}\n{render_nav()}\n{NAV_END}{tail}"


def orphan_pages() -> list[Path]:
    known = {s.main_name for s in TRANSLATION_SURFACES} | {"index.md"}
    if not SUTTA_DIR.exists():
        return []
    return [p for p in sorted(SUTTA_DIR.glob("*.md")) if p.name not in known]


# --------------------------------------------------------------------------
# entry points
# --------------------------------------------------------------------------

def check() -> list[str]:
    problems: list[str] = []
    for path, expected in planned_files().items():
        relative = path.relative_to(REPO_ROOT).as_posix()
        if not path.exists():
            problems.append(f"{relative}: missing")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            diff = list(difflib.unified_diff(
                actual.splitlines(), expected.splitlines(),
                lineterm="", n=1,
            ))[:8]
            problems.append(f"{relative}: stale\n    " + "\n    ".join(diff))
    try:
        if MKDOCS.read_text(encoding="utf-8") != planned_mkdocs():
            problems.append("mkdocs.yml: generated sutta nav is stale")
    except ValueError as error:
        problems.append(f"mkdocs.yml: {error}")
    for path in orphan_pages():
        problems.append(
            f"{path.relative_to(REPO_ROOT).as_posix()}: no registered surface"
        )
    return problems


def write() -> list[str]:
    written: list[str] = []
    SUTTA_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in planned_files().items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        path.write_text(content, encoding="utf-8", newline="\n")
        written.append(path.relative_to(REPO_ROOT).as_posix())
    nav = planned_mkdocs()
    if MKDOCS.read_text(encoding="utf-8") != nav:
        MKDOCS.write_text(nav, encoding="utf-8", newline="\n")
        written.append("mkdocs.yml")
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Fail if the reader is out of date.")
    parser.add_argument("--write", action="store_true",
                        help="Regenerate the reader.")
    args = parser.parse_args()

    if args.write:
        written = write()
        if written:
            for path in written:
                print(f"wrote {path}")
        else:
            print("Reader already up to date.")
        return 0

    problems = check()
    if not problems:
        print(
            f"Reader is current ({len(TRANSLATION_SURFACES)} surfaces, "
            f"{len(planned_files())} generated files)."
        )
        return 0
    print("Reader is out of date:")
    for problem in problems:
        print(f"- {problem}")
    print("")
    print("Run `python scripts/generate_reader.py --write` to regenerate.")
    return 1 if args.check else 0


if __name__ == "__main__":
    sys.exit(main())
