#!/usr/bin/env python3
"""Generate the reader's edition from the governed translation corpus.

The reader is a presentation layer, never a second source of truth. Everything
it shows about a sutta comes from two places:

  docs/translations/<surface>.md   the canonical governed translation
  scripts/surface_registry.py      reader metadata (title, stage, path note)

and one reader-authored part:

  the "About this text" block inside each reader page, which is preserved
  across regeneration and is the only hand-written prose in a sutta page.

Everything else -- the page title, the reference line, the translation body,
the reading-path navigation, the per-page glossary, the All Suttas index, the
Start Here path, the home page, the glossary page, and the site navigation --
is generated from those sources and is safe to regenerate at any time.

Usage:

    python scripts/generate_reader.py --check   verify the reader is current
    python scripts/generate_reader.py --write   regenerate it

`--check` is part of `run_checks.py`, so a reader that has drifted from the
governed corpus fails the build rather than going out stale.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

try:
    from scripts.surface_registry import (
        ESSENTIAL_FIVE,
        READER_METADATA,
        STAGES,
        TRANSLATION_SURFACES,
        TranslationSurface,
        REPO_ROOT,
        display_title,
        reader_meta,
        surfaces_in_reading_order,
    )
except ModuleNotFoundError:  # invoked as a script from the repo root
    from surface_registry import (  # type: ignore[no-redef]
        ESSENTIAL_FIVE,
        READER_METADATA,
        STAGES,
        TRANSLATION_SURFACES,
        TranslationSurface,
        REPO_ROOT,
        display_title,
        reader_meta,
        surfaces_in_reading_order,
    )


READER_DIR = REPO_ROOT / "reader-src"
SUTTA_DIR = READER_DIR / "suttas"
GLOSSARY_SOURCE = REPO_ROOT / "includes" / "glossary.md"
TERMS_DIR = REPO_ROOT / "terms"
MKDOCS = REPO_ROOT / "mkdocs.yml"

BODY_MARKER = "## Translation"
INTRO_HEADING = "about this text"
NAV_BEGIN = "  # BEGIN GENERATED SUTTA NAV"
NAV_END = "  # END GENERATED SUTTA NAV"

GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_reader.py. The translation body is a\n"
    "     presentation copy of the governed surface named above; edit that file,\n"
    "     not this one. The \"About this text\" section is reader-authored and is\n"
    "     preserved across regeneration. -->"
)

DEFAULT_INTRO = (
    "This text has not yet been given a reader's introduction. The translation "
    "below is the same governed text used throughout the project; only the "
    "orienting note is missing."
)


# --------------------------------------------------------------------------
# reading the canonical surface
# --------------------------------------------------------------------------

def surface_body(text: str) -> str:
    """The governed translation body, with headings demoted one level."""
    if BODY_MARKER not in text:
        raise ValueError(f"surface has no `{BODY_MARKER}` section")
    body = text.split(BODY_MARKER, 1)[1].strip()
    return re.sub(r"^### ", "## ", body, flags=re.M)


def existing_intro(path: Path) -> str | None:
    """The reader-authored `About this text` prose from an existing page."""
    if not path.exists():
        return None
    lines = path.read_text(encoding="utf-8").splitlines()
    start = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("## "):
            continue
        heading = stripped[3:].strip().casefold()
        if heading == INTRO_HEADING:
            start = index + 1
            continue
        if start is not None:
            return "\n".join(lines[start:index]).strip()
    if start is not None:
        return "\n".join(lines[start:]).strip()
    return None


# --------------------------------------------------------------------------
# per-page glossary
# --------------------------------------------------------------------------

def load_glossary() -> dict[str, str]:
    """Reader-facing term glosses, keyed by the English surface string.

    The source is `includes/glossary.md`, which is hand-written in reader voice
    on purpose. It is deliberately not the editorial `notes` field from the
    term records, which is written for contributors.
    """
    if not GLOSSARY_SOURCE.exists():
        return {}
    entries: dict[str, str] = {}
    for line in GLOSSARY_SOURCE.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\*\[([^\]]+)\]:\s*(.+)$", line.strip())
        if match:
            entries[match.group(1)] = match.group(2).strip()
    return entries


def glossary_for_page(body: str, glossary: dict[str, str]) -> list[tuple[str, str]]:
    """Only the glossary entries whose term actually appears on this page.

    Injecting per page rather than appending the whole glossary to every page
    is what makes a term able to carry a different note in a different sutta:
    the definition now travels with the page instead of being global.
    """
    found = []
    for term, gloss in sorted(glossary.items()):
        if re.search(rf"\b{re.escape(term)}\b", body):
            found.append((term, gloss))
    return found


def load_term_records() -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    if not TERMS_DIR.exists():
        return records
    for path in sorted(TERMS_DIR.rglob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        if isinstance(data, dict):
            records.append(data)
    return records


# --------------------------------------------------------------------------
# page rendering
# --------------------------------------------------------------------------

def render_sutta_page(
    surface: TranslationSurface,
    intro: str | None,
    glossary: dict[str, str],
    previous: TranslationSurface | None,
    following: TranslationSurface | None,
) -> str:
    meta = reader_meta(surface)
    body = surface_body(surface.main_path.read_text(encoding="utf-8"))
    stage_name = dict((n, t) for n, t, _ in STAGES)[meta.stage]

    lines = [
        GENERATED_BANNER,
        "",
        f"# {display_title(surface)}",
        "",
        f"*{surface.label}, the {meta.pali_title} — "
        f"stage {meta.stage}, {stage_name}*",
        "",
        "## About this text",
        "",
        intro.strip() if intro else DEFAULT_INTRO,
        "",
        body,
        "",
    ]

    # Sutta pages are siblings inside reader-src/suttas/, so these are bare
    # filenames rather than parent-relative paths.
    steps = []
    if previous is not None:
        steps.append(f"[← {display_title(previous)}]({previous.main_name})")
    steps.append("[All suttas](index.md)")
    if following is not None:
        steps.append(f"[{display_title(following)} →]({following.main_name})")
    lines.extend(["---", "", " · ".join(steps), ""])

    entries = glossary_for_page(body, glossary)
    if entries:
        lines.append("")
        for term, gloss in entries:
            lines.append(f"*[{term}]: {gloss}")
    return "\n".join(lines).rstrip() + "\n"


def render_home() -> str:
    total = len(TRANSLATION_SURFACES)
    by_key = {s.key: s for s in TRANSLATION_SURFACES}
    lines = [
        "# OSF Pali Readings",
        "",
        "Early Buddhist discourses in plain, contemporary English.",
        "",
        f"All {total} translations in this collection are readable here. Each "
        "one is backed by a governed Pali lexicon, so a term that matters is "
        "translated the same way every time it appears, and every translation "
        "decision has a written reason behind it. See "
        "[About this translation](about.md) for what that means in practice.",
        "",
        "## Start reading",
        "",
        "- [**Start Here**](start-here.md) — a newcomer-friendly reading order "
        f"through all {total} texts, arranged by what makes sense to read "
        "first rather than by editorial priority",
        "- [**All Suttas**](suttas/index.md) — the full collection, if you "
        "already know what you are looking for",
        "- [**Glossary**](glossary.md) — the recurring vocabulary, in plain "
        "English",
        "",
        "## If you only read five",
        "",
        "Together these give the whole shape of the teaching in under a "
        "thousand words:",
        "",
    ]
    for key in ESSENTIAL_FIVE:
        surface = by_key[key]
        meta = reader_meta(surface)
        lines.append(
            f"- [**{display_title(surface)}**](suttas/{surface.main_name}) — "
            f"{surface.label}, {meta.pali_title}"
        )
    lines.extend([
        "",
        "## How to read these",
        "",
        "The translations aim at ordinary spoken English: what a clear person "
        "would actually say, not what a translation is expected to sound like. "
        "Where a word is doing technical work, hover it for a short gloss.",
        "",
        "Repetition has been kept where the texts repeat. These were spoken "
        "and memorised, and the repeating is part of how they work.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def render_start_here() -> str:
    lines = [
        "# Start Here",
        "",
        f"A suggested order for reading the {len(TRANSLATION_SURFACES)} "
        "translations in this collection, for someone new to this material.",
        "",
        "This is deliberately **not** the project's internal translation "
        "roadmap. That roadmap ranks texts by editorial leverage — which "
        "translation next does the most to strengthen the lexicon. This page "
        "ranks the same texts by a different question: if you have never read "
        "early Buddhist material, what order actually makes sense? The two "
        "orderings often disagree, and that is expected.",
        "",
        "Every text below is readable on this site.",
        "",
    ]
    for number, title, blurb in STAGES:
        staged = [
            s for s in surfaces_in_reading_order()
            if reader_meta(s).stage == number
        ]
        lines.extend([f"## Stage {number} — {title}", "", blurb, ""])
        for surface in staged:
            meta = reader_meta(surface)
            label = display_title(surface)
            suffix = (
                f" ({surface.label}, {meta.pali_title})"
                if meta.reader_title
                else ""
            )
            lines.append(
                f"- [**{label}**](suttas/{surface.main_name}){suffix} — "
                f"{meta.path_note}"
            )
        lines.append("")

    by_key = {s.key: s for s in TRANSLATION_SURFACES}
    names = ", ".join(
        f"[{display_title(by_key[k])}](suttas/{by_key[k].main_name})"
        for k in ESSENTIAL_FIVE
    )
    lines.extend([
        "## If you only read five",
        "",
        f"{names}. That is the whole shape of the teaching — test it "
        "yourself, some questions are not the point, here is the diagnosis, "
        "here is how pain and suffering differ, here is why \"self\" does not "
        "hold up under examination.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def render_all_suttas() -> str:
    lines = [
        "# All Suttas",
        "",
        f"All {len(TRANSLATION_SURFACES)} translations, grouped by collection. "
        "If you would rather be guided, use [Start Here](../start-here.md).",
        "",
    ]
    collections = [
        ("DN", "Dīgha Nikāya", "the long discourses"),
        ("MN", "Majjhima Nikāya", "the middle-length discourses"),
        ("SN", "Saṁyutta Nikāya", "the connected discourses"),
        ("AN", "Aṅguttara Nikāya", "the numbered discourses"),
    ]

    def sort_key(surface: TranslationSurface) -> tuple[int, int]:
        numbers = re.findall(r"\d+", surface.label)
        major = int(numbers[0]) if numbers else 0
        minor = int(numbers[1]) if len(numbers) > 1 else 0
        return major, minor

    for prefix, pali, gloss in collections:
        group = sorted(
            (s for s in TRANSLATION_SURFACES if s.label.startswith(prefix + " ")),
            key=sort_key,
        )
        if not group:
            continue
        lines.extend([f"## {pali} ({prefix}) — {gloss}", ""])
        lines.append("| Reference | Title | Stage | What it covers |")
        lines.append("| --- | --- | --- | --- |")
        for surface in group:
            meta = reader_meta(surface)
            title = f"[{display_title(surface)}]({surface.main_name})"
            pali_note = (
                f"<br><small>{meta.pali_title}</small>" if meta.reader_title else ""
            )
            note = meta.path_note.split(".")[0].strip() + "."
            lines.append(
                f"| {surface.label} | {title}{pali_note} | {meta.stage} | {note} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_glossary() -> str:
    glossary = load_glossary()
    records = load_term_records()

    by_rendering: dict[str, dict[str, object]] = {}
    for record in records:
        preferred = record.get("preferred_translation")
        if isinstance(preferred, str):
            by_rendering.setdefault(preferred.casefold(), record)

    lines = [
        "# Glossary",
        "",
        "The recurring vocabulary of these translations, in plain English.",
        "",
        "Every term here is governed: the project fixes one English rendering "
        "for each Pali term and uses it consistently, so that a word carrying "
        "technical weight does not quietly change meaning between texts. The "
        "explanations below are written for readers. The editorial reasoning "
        "behind each choice lives in the "
        "[repository](https://github.com/timedrapery/shiny-adventure/tree/main/terms).",
        "",
        "Terms also appear as hover notes inside each sutta.",
        "",
        "| Term used here | Pali | In plain English |",
        "| --- | --- | --- |",
    ]
    for term, gloss in sorted(glossary.items(), key=lambda kv: kv[0].casefold()):
        record = by_rendering.get(term.casefold())
        pali = ""
        if record is not None and isinstance(record.get("term"), str):
            pali = f"`{record['term']}`"
        lines.append(f"| {term} | {pali} | {gloss} |")

    lines.extend([
        "",
        "## Terms deliberately left in Pali",
        "",
        "A few words are kept in Pali because every English option narrows "
        "them misleadingly. Where that is the case, the surrounding text is "
        "written so the sense is still followable.",
        "",
        "`bhikkhu`, `dhamma`, `nibbāna`, and `Tathāgata` are the main ones.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def render_nav() -> str:
    lines = []
    for number, title, _ in STAGES:
        staged = [
            s for s in surfaces_in_reading_order()
            if reader_meta(s).stage == number
        ]
        if not staged:
            continue
        lines.append(f"      - Stage {number}. {title}:")
        for surface in staged:
            label = display_title(surface).replace('"', "'")
            lines.append(f'          - "{label}": suttas/{surface.main_name}')
    return "\n".join(lines)


# --------------------------------------------------------------------------
# planning
# --------------------------------------------------------------------------

def planned_files() -> dict[Path, str]:
    """Every file the generator owns, mapped to its intended content."""
    glossary = load_glossary()
    ordered = surfaces_in_reading_order()
    planned: dict[Path, str] = {
        READER_DIR / "index.md": render_home(),
        READER_DIR / "start-here.md": render_start_here(),
        READER_DIR / "glossary.md": render_glossary(),
        SUTTA_DIR / "index.md": render_all_suttas(),
    }
    for position, surface in enumerate(ordered):
        page = SUTTA_DIR / surface.main_name
        planned[page] = render_sutta_page(
            surface,
            existing_intro(page),
            glossary,
            ordered[position - 1] if position else None,
            ordered[position + 1] if position + 1 < len(ordered) else None,
        )
    return planned


def planned_mkdocs() -> str:
    text = MKDOCS.read_text(encoding="utf-8")
    if NAV_BEGIN not in text or NAV_END not in text:
        raise ValueError("mkdocs.yml is missing the generated nav markers")
    head, rest = text.split(NAV_BEGIN, 1)
    _, tail = rest.split(NAV_END, 1)
    return f"{head}{NAV_BEGIN}\n{render_nav()}\n{NAV_END}{tail}"


def orphan_pages() -> list[Path]:
    known = {s.main_name for s in TRANSLATION_SURFACES} | {"index.md"}
    if not SUTTA_DIR.exists():
        return []
    return [p for p in sorted(SUTTA_DIR.glob("*.md")) if p.name not in known]


# --------------------------------------------------------------------------
# entry points
# --------------------------------------------------------------------------

def check() -> list[str]:
    problems: list[str] = []
    for path, expected in planned_files().items():
        relative = path.relative_to(REPO_ROOT).as_posix()
        if not path.exists():
            problems.append(f"{relative}: missing")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            diff = list(difflib.unified_diff(
                actual.splitlines(), expected.splitlines(),
                lineterm="", n=1,
            ))[:8]
            problems.append(f"{relative}: stale\n    " + "\n    ".join(diff))
    try:
        if MKDOCS.read_text(encoding="utf-8") != planned_mkdocs():
            problems.append("mkdocs.yml: generated sutta nav is stale")
    except ValueError as error:
        problems.append(f"mkdocs.yml: {error}")
    for path in orphan_pages():
        problems.append(
            f"{path.relative_to(REPO_ROOT).as_posix()}: no registered surface"
        )
    return problems


def write() -> list[str]:
    written: list[str] = []
    SUTTA_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in planned_files().items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        path.write_text(content, encoding="utf-8", newline="\n")
        written.append(path.relative_to(REPO_ROOT).as_posix())
    nav = planned_mkdocs()
    if MKDOCS.read_text(encoding="utf-8") != nav:
        MKDOCS.write_text(nav, encoding="utf-8", newline="\n")
        written.append("mkdocs.yml")
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Fail if the reader is out of date.")
    parser.add_argument("--write", action="store_true",
                        help="Regenerate the reader.")
    args = parser.parse_args()

    if args.write:
        written = write()
        if written:
            for path in written:
                print(f"wrote {path}")
        else:
            print("Reader already up to date.")
        return 0

    problems = check()
    if not problems:
        print(
            f"Reader is current ({len(TRANSLATION_SURFACES)} surfaces, "
            f"{len(planned_files())} generated files)."
        )
        return 0
    print("Reader is out of date:")
    for problem in problems:
        print(f"- {problem}")
    print("")
    print("Run `python scripts/generate_reader.py --write` to regenerate.")
    return 1 if args.check else 0


if __name__ == "__main__":
    sys.exit(main())
